### ISSUE TITLE
Dejar el cable amarillo de la camara

### ISSUE THREAD

**Issue by kbm15** [asrob-uc3m/Taller-de-Papa-Noel#1]
Se especifica que en el taller se va a dejar el cable amarillo.
Este cable pesa cerca de medio gramo y se puede ahorrar en la build final desoldandolo.

**Comment by David-Estevez** [comment]
Extraído del texto del README:

> Este modelo tiene capacidad para utilizar OSD con los cables amarillo y blanco, pero como nuestro dron no lo soporta los dejaremos sueltos. También pueden cortarse directamente.
